# This is a basic workflow to help you get started with Actions

name: Running pilot pipeline every minute

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: 2248932573,
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "ubuntu-pilot-cli"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/ubuntu-pilot-cli.zip', Buffer.from(download.data));

      -name: unzip cli
        run: |
          unzip ubuntu-pilot-cli.zip && chmod +x ./pilot-cli

      # Runs a single command using the runners shell
      - name: Fetch binance price
        run: |
          RUST_LOG=pilot_pipeline=info ./pilot-cli fetch-price  \
              --endpoint-auth-user "${{ secrets.USER }}" \
              --endpoint-auth-pass "${{ secrets.PASS }}" \
              --endpoint-uri https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push

      # Runs a single command using the runners shell
      - name: Fetch binance orderbook
        run: |
          RUST_LOG=pilot_pipeline=info ./pilot-cli fetch-orderbook  \
          --lc-baseuri https://prfqn7ty.api.lncldglobal.com \
          --lc-id ${{ secrets.LC_ID }} \
          --lc-key ${{ secrets.LC_KEY }} \
          --symbols=BTCUSDT=100.0 \
          --symbols=ETHUSDT=10.0
