on:
  release:
    types: [created]

jobs:
  release:
    name: release pilot pipeline ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-pilot-cli
          path: ./target/release/pilot-cli