# This is a basic workflow to help you get started with Actions

name: Running pilot pipeline every minute

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '* * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "detailyang/pilot"
          version: "tags/v0.1"
          file: "pilot_v0.1_x86_64-unknown-linux-musl.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - name: Fetch binance 24h avg price
        run: |
          tar -zxf pilot_v0.1_x86_64-unknown-linux-musl.tar.gz 
          mkdir -p config; touch config/symbols
          RUST_LOG=pilot_pipeline=info ./pilot-cli pipeline --endpoint-auth-user 405130 --endpoint-auth-pass eyJrIjoiMjA3MTJlNjVjZDIxNWY3OTExMmE4YTIyMTMzOGE1ZWMzNjhhNmQ1NCIsIm4iOiJ0ZXN0IiwiaWQiOjQxOTg2M30= --endpoint-uri https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push --once --symbols config/symbols --workers 2
